-- MinwonON ERD DDL
-- 기준일: 2026-08-18
-- 기준 문서:
-- 1) docs/contracts/backend-a-domain-contract-freeze.md
-- 2) docs/api-spec.md
--
-- DB 엔진: PostgreSQL 16+
-- 원칙:
-- - 서비스별 DB 분리
-- - 같은 서비스 내부에서만 FK 사용
-- - 다른 서비스 엔티티는 ID 논리 참조만 사용
-- - 첨부파일 원본은 S3, DB에는 메타데이터만 저장

-- =====================================================================
-- 0. DATABASE 생성
-- =====================================================================
-- 아래 CREATE DATABASE는 postgres 기본 DB 등 별도 세션에서 실행하세요.

CREATE DATABASE user_db;
CREATE DATABASE assignment_db;
CREATE DATABASE complaint_db;
CREATE DATABASE notification_db;
CREATE DATABASE statistics_db;

-- =====================================================================
-- 1. user_db
-- =====================================================================

\connect user_db;

CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login_id VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    phone VARCHAR(30) NOT NULL,
    role VARCHAR(20) NOT NULL,
    department_id BIGINT NULL,
    email_notify_agreed BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_users_role
        CHECK (role IN ('CITIZEN', 'OFFICER', 'ADMIN'))
);

CREATE INDEX IF NOT EXISTS idx_users_department_id ON users (department_id);
CREATE INDEX IF NOT EXISTS idx_users_role ON users (role);

-- =====================================================================
-- 2. assignment_db
-- =====================================================================

\connect assignment_db;

CREATE TABLE IF NOT EXISTS departments (
    department_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_name VARCHAR(100) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS complaint_categories (
    category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name VARCHAR(100) NOT NULL,
    category_code VARCHAR(50) NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS department_categories (
    department_category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    officer_user_id BIGINT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_department_categories_department
        FOREIGN KEY (department_id) REFERENCES departments (department_id),
    CONSTRAINT fk_department_categories_category
        FOREIGN KEY (category_id) REFERENCES complaint_categories (category_id),
    CONSTRAINT uq_department_categories_mapping
        UNIQUE (department_id, category_id, officer_user_id)
);

CREATE INDEX IF NOT EXISTS idx_department_categories_department_id
    ON department_categories (department_id);
CREATE INDEX IF NOT EXISTS idx_department_categories_category_id
    ON department_categories (category_id);
CREATE INDEX IF NOT EXISTS idx_department_categories_officer_user_id
    ON department_categories (officer_user_id);

-- =====================================================================
-- 3. complaint_db
-- =====================================================================

\connect complaint_db;

CREATE TABLE IF NOT EXISTS complaints (
    complaint_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    complaint_no VARCHAR(50) NOT NULL UNIQUE,
    applicant_user_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    assigned_department_id BIGINT NULL,
    assigned_officer_user_id BIGINT NULL,
    title VARCHAR(200) NOT NULL,
    content TEXT NOT NULL,
    current_status VARCHAR(20) NOT NULL,
    submitted_at TIMESTAMP NOT NULL,
    assigned_at TIMESTAMP NULL,
    completed_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_complaints_current_status
        CHECK (current_status IN ('RECEIVED', 'ASSIGNED', 'IN_PROGRESS', 'COMPLETED'))
);

CREATE INDEX IF NOT EXISTS idx_complaints_applicant_user_id
    ON complaints (applicant_user_id);
CREATE INDEX IF NOT EXISTS idx_complaints_category_id
    ON complaints (category_id);
CREATE INDEX IF NOT EXISTS idx_complaints_assigned_department_id
    ON complaints (assigned_department_id);
CREATE INDEX IF NOT EXISTS idx_complaints_assigned_officer_user_id
    ON complaints (assigned_officer_user_id);
CREATE INDEX IF NOT EXISTS idx_complaints_current_status
    ON complaints (current_status);
CREATE INDEX IF NOT EXISTS idx_complaints_submitted_at
    ON complaints (submitted_at);

CREATE TABLE IF NOT EXISTS complaint_attachments (
    attachment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    complaint_id BIGINT NOT NULL,
    original_filename VARCHAR(255) NOT NULL,
    stored_filename VARCHAR(255) NOT NULL,
    file_path VARCHAR(500) NOT NULL,
    content_type VARCHAR(100) NOT NULL,
    file_size BIGINT NOT NULL,
    uploaded_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_complaint_attachments_complaint
        FOREIGN KEY (complaint_id) REFERENCES complaints (complaint_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_complaint_attachments_complaint_id
    ON complaint_attachments (complaint_id);

CREATE TABLE IF NOT EXISTS complaint_status_history (
    status_history_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    complaint_id BIGINT NOT NULL,
    previous_status VARCHAR(20) NULL,
    new_status VARCHAR(20) NOT NULL,
    changed_by_user_id BIGINT NULL,
    change_memo VARCHAR(255) NULL,
    changed_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_complaint_status_history_complaint
        FOREIGN KEY (complaint_id) REFERENCES complaints (complaint_id) ON DELETE CASCADE,
    CONSTRAINT chk_complaint_status_history_previous_status
        CHECK (
            previous_status IS NULL
            OR previous_status IN ('RECEIVED', 'ASSIGNED', 'IN_PROGRESS', 'COMPLETED')
        ),
    CONSTRAINT chk_complaint_status_history_new_status
        CHECK (new_status IN ('RECEIVED', 'ASSIGNED', 'IN_PROGRESS', 'COMPLETED'))
);

CREATE INDEX IF NOT EXISTS idx_complaint_status_history_complaint_id
    ON complaint_status_history (complaint_id);
CREATE INDEX IF NOT EXISTS idx_complaint_status_history_changed_at
    ON complaint_status_history (changed_at);

CREATE TABLE IF NOT EXISTS complaint_responses (
    response_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    complaint_id BIGINT NOT NULL,
    responder_user_id BIGINT NOT NULL,
    response_content TEXT NOT NULL,
    is_public BOOLEAN NOT NULL DEFAULT FALSE,
    responded_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_complaint_responses_complaint
        FOREIGN KEY (complaint_id) REFERENCES complaints (complaint_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_complaint_responses_complaint_id
    ON complaint_responses (complaint_id);
CREATE INDEX IF NOT EXISTS idx_complaint_responses_is_public
    ON complaint_responses (is_public);
CREATE INDEX IF NOT EXISTS idx_complaint_responses_responded_at
    ON complaint_responses (responded_at);

-- =====================================================================
-- 4. notification_db
-- =====================================================================

\connect notification_db;

CREATE TABLE IF NOT EXISTS notifications (
    notification_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receiver_user_id BIGINT NOT NULL,
    complaint_id BIGINT NOT NULL,
    notification_type VARCHAR(30) NOT NULL,
    channel VARCHAR(20) NOT NULL,
    title VARCHAR(200) NOT NULL,
    message VARCHAR(1000) NOT NULL,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    read_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_notifications_notification_type
        CHECK (notification_type IN ('ASSIGNED', 'STATUS_CHANGED', 'RESPONSE_REGISTERED')),
    CONSTRAINT chk_notifications_channel
        CHECK (channel IN ('IN_APP', 'EMAIL'))
);

CREATE INDEX IF NOT EXISTS idx_notifications_receiver_user_id
    ON notifications (receiver_user_id);
CREATE INDEX IF NOT EXISTS idx_notifications_complaint_id
    ON notifications (complaint_id);
CREATE INDEX IF NOT EXISTS idx_notifications_is_read
    ON notifications (is_read);
CREATE INDEX IF NOT EXISTS idx_notifications_created_at
    ON notifications (created_at);

-- =====================================================================
-- 5. statistics_db
-- =====================================================================

\connect statistics_db;

CREATE TABLE IF NOT EXISTS daily_complaint_statistics (
    statistics_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    statistics_date DATE NOT NULL,
    department_id BIGINT NOT NULL,
    received_count BIGINT NOT NULL DEFAULT 0,
    assigned_count BIGINT NOT NULL DEFAULT 0,
    in_progress_count BIGINT NOT NULL DEFAULT 0,
    completed_count BIGINT NOT NULL DEFAULT 0,
    avg_processing_time DECIMAL(12, 2) NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_daily_complaint_statistics
        UNIQUE (statistics_date, department_id)
);

CREATE INDEX IF NOT EXISTS idx_daily_complaint_statistics_date
    ON daily_complaint_statistics (statistics_date);
CREATE INDEX IF NOT EXISTS idx_daily_complaint_statistics_department_id
    ON daily_complaint_statistics (department_id);

-- =====================================================================
-- 6. 참고 메모
-- =====================================================================
-- 1) complaint_db.category_id 는 assignment_db.complaint_categories.category_id 를 논리 참조합니다.
-- 2) complaint_db.assigned_department_id 는 assignment_db.departments.department_id 를 논리 참조합니다.
-- 3) complaint_db.applicant_user_id, assigned_officer_user_id, responder_user_id 는 user_db.users.user_id 를 논리 참조합니다.
-- 4) notification_db.receiver_user_id 도 user_db.users.user_id 를 논리 참조합니다.
-- 5) statistics_db.department_id 는 assignment_db.departments.department_id 를 논리 참조합니다.
-- 6) 서비스 간 FK는 MSA 원칙상 걸지 않습니다.
