spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3310/${USER_DB_NAME:user_db}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8}
    username: ${DB_USERNAME:${USER_DB_USER:user}}
    password: ${DB_PASSWORD:${USER_DB_PASSWORD:}}
    driver-class-name: ${DB_DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:validate}
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul
  flyway:
    enabled: ${FLYWAY_ENABLED:true}

logging:
  level:
    root: INFO
    com.gcivil: INFO
