server:
  port: ${SERVER_PORT:8085}
spring:
  application:
    name: statistics-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
management:
  endpoints:
    web:
      exposure:
        include: health,info

statistics:
  metrics:
    processing-deadline-days: ${STATISTICS_PROCESSING_DEADLINE_DAYS:7}
    deadline-approaching-days: ${STATISTICS_DEADLINE_APPROACHING_DAYS:2}
